#!/bin/sh
### BEGIN INIT INFO
# Provides:          energomera_ce307
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       later
### END INIT INFO 

# nano /etc/init.d/energomera_ce307
# chmod +x /etc/init.d/energomera_ce307
# update-rc.d -f energomera_ce307 defaults
# service energomera_ce307 start

SCRIPT="/usr/bin/python3 -u /home/komp108/energomera_ce307/energomera_ce307.py"
RUNAS="root"

PIDFILE=/var/run/energomera_ce307.pid
LOGFILE=/var/log/energomera_ce307.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT >> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

#status() {
#  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
#    log_action_msg "Service is running"
#    echo 0
#  else
#    log_action_msg "Service is not running"
#    echo 3
#  fi
#}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f <NAME> remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
#  status)
#    status
#    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|uninstall}"
esac

